using System;
using Content.Client._CMU14.Interface;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Voting.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VotePopup : Control
    {
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IVoteManager _voteManager = default!;
        [Dependency] private IEntityNetworkManager _net = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;

        private readonly VoteManager.ActiveVote _vote;
        private readonly Button[] _voteButtons;
        // Only populated under CRT, where each option is a bar with its count on the right.
        private readonly Label[] _voteCounts;
        private readonly NetEntity? _targetEntity;
        private int _optionColumns = -1;
        private int _optionMinWidth = -1;
        private int _optionMinHeight = -1;

        private const int CompactOptionMinWidth = 220;
        private const int WideOptionMinWidth = 400;
        private const int SingleOptionMinWidth = 560;
        private const int OptionMinHeight = 34;
        private const int TallOptionMinHeight = 48;
        private const int WideOptionTextLength = 24;
        private const int VeryWideOptionTextLength = 42;
        private const int TallOptionTextLength = 32;

        /// <summary>
        ///     Matches HSeparationOverride on VoteOptionsContainer. Needed here to work out how many
        ///     columns actually fit.
        /// </summary>
        private const int OptionSeparation = 8;

        /// <summary>
        ///     Horizontal margin on MainContent, doubled. The options have this much less room than
        ///     the popup itself.
        /// </summary>
        private const int ContentHorizontalMargin = 28;

        private const float LargeUiScale = 1.35f;

        private float OptionScale => _cfg.GetCVar(CCVars.CMUVoteUiLarge) ? LargeUiScale : 1f;

        public VotePopup(VoteManager.ActiveVote vote)
        {
            _vote = vote;
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
            _cfg.OnValueChanged(CCVars.CMUVoteUiLarge, OnVoteUiLargeChanged);

            if (_vote.TargetEntity != null && _vote.TargetEntity != 0)
            {
                _targetEntity = new NetEntity(_vote.TargetEntity.Value);
                FollowVoteTarget.Visible = true;
                FollowVoteTarget.OnPressed += _ => AttemptFollowVoteEntity();
            }

            Modulate = Color.White.WithAlpha(0.96f);
            _voteButtons = new Button[vote.Entries.Length];
            _voteCounts = new Label[vote.Entries.Length];
            var group = new ButtonGroup();

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var button = new Button
                {
                    ToggleMode = true,
                    Group = group,
                    HorizontalExpand = true,
                    MinHeight = OptionMinHeight,
                    ClipText = false,
                    RectClipContent = false,
                    TextAlign = StyleNano.CrtUiEnabled ? Label.AlignMode.Left : Label.AlignMode.Center,
                    StyleClasses = { StyleNano.StyleClassCrtButton }
                };
                button.Label.AddStyleClass(StyleNano.StyleClassCrtButtonLabel);
                button.Label.HorizontalExpand = true;
                button.Label.VAlign = Label.VAlignMode.Center;

                if (StyleNano.CrtUiEnabled)
                {
                    // The count is its own label so it can sit hard right while the name stays left -
                    // a Button has exactly one Label and it cannot align two things at once.
                    var count = new Label
                    {
                        HorizontalAlignment = HAlignment.Right,
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(0, 0, 10, 0),
                    };
                    count.AddStyleClass(StyleNano.StyleClassCrtButtonLabel);
                    button.AddChild(count);
                    _voteCounts[i] = count;
                }

                _voteButtons[i] = button;
                VoteOptionsContainer.AddChild(button);
                var i1 = i;
                button.OnPressed += _ => _voteManager.SendCastVote(vote.Id, i1);
            }

            MinimizeButton.OnPressed += _ => SetMinimized(true);
            RestoreButton.OnPressed += _ => SetMinimized(false);
            ReflowOptions(GetRawOptionTexts());
        }

        protected override void Resized()
        {
            base.Resized();

            // Column count depends on how much room we actually got, and that isn't known until the
            // first layout pass - nor when the window or the lobby split is resized afterwards.
            ReflowOptions(GetRawOptionTexts());
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
            _cfg.UnsubValueChanged(CCVars.CMUVoteUiLarge, OnVoteUiLargeChanged);
        }

        private void OnVoteUiLargeChanged(bool _)
        {
            // Reset the cache or ReflowOptions decides nothing changed and returns early.
            _optionColumns = -1;
            ReflowOptions(GetRawOptionTexts());
        }

        private void OnCrtUiEnabledChanged(bool _)
        {
            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
        }

        private void OnCrtUiColorChanged(string _)
        {
            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            VotePanel.PanelOverride = CreateVotePanelStyleBox();
        }

        private static CrtStyleBox CreateVotePanelStyleBox()
        {
            return new CrtStyleBox
            {
                BackgroundColor = StyleNano.CrtPanelBackground,
                BorderColor = StyleNano.CrtGreenDim,
                CornerColor = StyleNano.CrtGreen.WithAlpha(0.28f),
                BorderThickness = new Thickness(1),
                CornerLength = 10,
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8
            };
        }

        public void UpdateData()
        {
            VoteTitle.SetMessage(FormattedMessage.FromUnformatted(_vote.Title));
            VoteCaller.Text = Loc.GetString("ui-vote-created", ("initiator", _vote.Initiator));
            MinimizedTitle.Text = _vote.Title;
            var buttonTexts = new string[_voteButtons.Length];

            // Total, not max: a bar should read as this option's share of the vote, so a lone vote in
            // a four-way split is a quarter bar rather than a full one.
            var totalVotes = 0;
            foreach (var e in _vote.Entries)
            {
                totalVotes += e.Votes;
            }

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var entry = _vote.Entries[i];
                string buttonText;
                if (_vote.DisplayVotes)
                {
                    buttonText = Loc.GetString("ui-vote-button", ("text", entry.Text), ("votes", entry.Votes));
                }
                else
                {
                    buttonText = Loc.GetString("ui-vote-button-no-votes", ("text", entry.Text));
                }

                // Reflow still measures the combined string. It is what decides how wide an option
                // has to be, and under CRT the name and the count are drawn at opposite ends of that
                // same width - so the text it measures has to include both.
                buttonTexts[i] = buttonText;
                _voteButtons[i].ToolTip = buttonText;

                if (StyleNano.CrtUiEnabled)
                {
                    _voteButtons[i].Text = entry.Text;
                    _voteButtons[i].StyleBoxOverride = new CmuVoteBarStyleBox
                    {
                        TrackColor = CrtTerminalPalette.Surface1,
                        FillColor = CrtTerminalPalette.Surface3,
                        AccentColor = CrtTerminalPalette.Accent,
                        Fraction = totalVotes > 0 ? entry.Votes / (float) totalVotes : 0f,
                        IsOurVote = _vote.OurVote == i,
                    };

                    if (_voteCounts[i] is { } count)
                    {
                        count.Text = _vote.DisplayVotes ? entry.Votes.ToString() : string.Empty;
                        count.FontColorOverride = entry.Votes > 0
                            ? CrtTerminalPalette.TextBright
                            : CrtTerminalPalette.TextDim;
                    }
                }
                else
                {
                    _voteButtons[i].Text = buttonText;
                }

                if (_vote.OurVote == i)
                    _voteButtons[i].Pressed = true;
            }

            ReflowOptions(buttonTexts);
        }

        private string[] GetRawOptionTexts()
        {
            var texts = new string[_vote.Entries.Length];
            for (var i = 0; i < _vote.Entries.Length; i++)
            {
                texts[i] = _vote.Entries[i].Text;
            }

            return texts;
        }

        private void ReflowOptions(string[] texts)
        {
            if (texts.Length == 0)
                return;

            var scale = OptionScale;
            var longest = GetLongestTextLine(texts);
            // One column under CRT. The options are bars now, and bars are only comparable when they
            // share a baseline and a width - side by side in three columns they are four unrelated
            // rectangles rather than one chart.
            var columns = StyleNano.CrtUiEnabled ? 1 : GetOptionColumns(texts.Length, longest, scale);
            var minWidth = (int) (GetOptionMinWidth(columns, longest) * scale);
            var minHeight = (int) ((longest > TallOptionTextLength ? TallOptionMinHeight : OptionMinHeight) * scale);

            if (_optionColumns == columns &&
                _optionMinWidth == minWidth &&
                _optionMinHeight == minHeight)
            {
                return;
            }

            _optionColumns = columns;
            _optionMinWidth = minWidth;
            _optionMinHeight = minHeight;

            VoteOptionsContainer.Columns = columns;

            foreach (var button in _voteButtons)
            {
                button.MinWidth = minWidth;
                button.MinHeight = minHeight;
                button.ClipText = false;
                button.RectClipContent = false;
            }
        }

        private int GetOptionColumns(int optionCount, int longestText, float scale)
        {
            if (optionCount <= 1)
                return 1;

            var preferred = longestText switch
            {
                > VeryWideOptionTextLength => 1,
                > WideOptionTextLength => 2,
                _ => Math.Min(3, optionCount),
            };

            // Clamp against the width actually available. Picking a column count purely from text
            // length is what let the options run past the panel: the popup sets RectClipContent, so
            // a column that doesn't fit is a button with its label sliced off rather than a row that
            // wraps. Width is zero until the first layout pass, so fall back to the preference then
            // and let Resized correct it.
            var available = Width - ContentHorizontalMargin;
            if (available <= 0)
                return preferred;

            var columnWidth = CompactOptionMinWidth * scale + OptionSeparation;
            var fits = (int) ((available + OptionSeparation) / columnWidth);

            return Math.Clamp(fits, 1, preferred);
        }

        private static int GetOptionMinWidth(int columns, int longestText)
        {
            if (columns == 1)
                return Math.Max(SingleOptionMinWidth, 12 * longestText);

            if (longestText > WideOptionTextLength)
                return Math.Max(WideOptionMinWidth, 10 * longestText);

            return CompactOptionMinWidth;
        }

        private static int GetLongestTextLine(string[] texts)
        {
            var longest = 0;
            foreach (var text in texts)
            {
                var lineStart = 0;
                for (var i = 0; i <= text.Length; i++)
                {
                    if (i != text.Length && text[i] != '\n')
                        continue;

                    longest = Math.Max(longest, i - lineStart);
                    lineStart = i + 1;
                }
            }

            return longest;
        }

        private void AttemptFollowVoteEntity()
        {
            if (_targetEntity != null)
            {
                var msg = new GhostWarpToTargetRequestEvent(_targetEntity.Value);
                _net.SendSystemNetworkMessage(msg);
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            // Logger.GetSawmill("content").Debug($"{_gameTiming.ServerTime}, {_vote.StartTime}, {_vote.EndTime}");

            var curTime = _gameTiming.RealTime;
            var timeLeft = _vote.EndTime - curTime;
            if (timeLeft < TimeSpan.Zero)
                timeLeft = TimeSpan.Zero;

            // Round up a second.
            timeLeft = TimeSpan.FromSeconds(Math.Ceiling(timeLeft.TotalSeconds));

            TimeLeftBar.Value = Math.Min(1, (float) ((curTime.TotalSeconds - _vote.StartTime.TotalSeconds)
                / (_vote.EndTime.TotalSeconds - _vote.StartTime.TotalSeconds)));

            TimeLeftText.Text = $"{timeLeft:m\\:ss}";
            if (MinimizedContent.Visible)
                MinimizedTimeLeft.Text = $"{timeLeft:m\\:ss}";
        }

        private void SetMinimized(bool minimized)
        {
            MainContent.Visible = !minimized;
            MinimizedContent.Visible = minimized;

            if (minimized)
            {
                MinWidth = 280;
                MaxWidth = 400;
                MinimizedTitle.Text = _vote.Title;
            }
            else
            {
                MinWidth = 560;
                MaxWidth = 1280;
            }
        }
    }
}
