- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  id: AU14JobSquadRiflemanBaseAbstract # Rifleman Abstraction
  name: au14-job-name-govforsquadrifleman
  description: au14-job-description-govforsquadrifleman
  icon: "AU14JobIconGovRifleman"
  spawnMenuRoleName: Rifleman (GOVFOR)
  startingGear: AU14GearGOVFORSquadRifleman
  dummyStartingGear: AU14GearGOVFORRiflemanDummy
  playTimeTracker: AU14JobGOVFORSquadRifleman
  accessGroups:
  - AU14GovforSquad
  hasIcon: false

- type: job
  abstract: true
  parent: AU14JobSquadRiflemanBaseAbstract
  id: AU14JobSquadRiflemanBase # Rifleman Base
  roundRole: SquadRifleman
  roundProfiles:
  - AU14RoundJobProfileSquadRifleman
  roundComponents:
  - type: Skills
    preset: AU14SkillPresetPlatoonRifleman
  - type: JobPrefix
    prefix: au14-job-prefix-govforsquadrifleman
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14govforjobicons.rsi
      state: rifleman
  roundForceComponents:
    OPFOR:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforjobicons.rsi
        state: rifleman
    RMC:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
    UPP:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanUPP
    CMBCIU:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 2
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanCMBCIU
    WYPMC:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanWYPMC

  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankPrivateFirstClass:
      entity: AU14ChevronUSCMPrivateFirstClass
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadRifleman
        time: 36000 # 10 hours
    RMCRankPrivate:
      entity: AU14ChevronUSCMPrivate
      requirements: []
- type: playTimeTracker
  id: AU14JobGOVFORSquadRifleman
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORSquadRifleman
  equipment:
    id: AU14IDCardSquadRifleman
    ears: AU14HeadsetGovforMarine

- type: startingGear
  id: AU14GearGOVFORRiflemanDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetGovforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSquadRifleman
  name: Spawn Point GOVFOR Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSquadRifleman
  - type: Sprite
    state: syn_spawn

- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  id: AU14JobSquadAutomaticRiflemanBaseAbstract
  name: au14-job-name-govforsquadautomaticrifleman
  description: au14-job-description-govforsquadautomaticrifleman
  icon: "AU14JobIconAFN"
  spawnMenuRoleName: Automatic Rifleman (GOVFOR)
  startingGear: AU14GearGOVFORSquadAutomaticRifleman
  dummyStartingGear: AU14GearGOVFORAutoRiflemanDummy
  playTimeTracker: AU14JobGOVFORSquadAutomaticRifleman
  overwatchRoleName: au14-job-name-govforsquadautomaticrifleman-plural
  overwatchSortPriority: -6
  overwatchShowName: true
  accessGroups:
  - AU14GovforGunner

- type: job
  abstract: true
  parent: AU14JobSquadAutomaticRiflemanBaseAbstract
  id: AU14JobSquadAutomaticRiflemanBase
  roundRole: SquadAutomaticRifleman
  roundProfiles:
  - AU14RoundJobProfileMilitaryBase
  roundComponents:
  - type: SquadArmorWearer
  - type: Skills
    preset: AU14SkillPresetPlatoonAutomaticRifleman
  - type: JobPrefix
    prefix: au14-job-prefix-govforsquadautomaticrifleman
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14govforjobicons.rsi
      state: govfor_afn
  roundForceComponents:
    OPFOR:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforjobicons.rsi
        state: afn
    UPP:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillSmartGun: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadAutomaticRiflemanUPP
    WYPMC:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillSmartGun: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadAutomaticRiflemanWYPMC

  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankLanceCorporal:
      entity: AU14ChevronUSCMLanceCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadAutomaticRifleman
        time: 86400 # 24 hours
    RMCRankPrivateFirstClass:
      entity: AU14ChevronUSCMPrivateFirstClass
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadAutomaticRifleman
        time: 36000 # 10 hours
    RMCRankPrivate:
      entity: AU14ChevronUSCMPrivate
      requirements: []
- type: playTimeTracker
  id: AU14JobGOVFORSquadAutomaticRifleman
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORSquadAutomaticRifleman
  equipment:
    id: AU14IDCardSquadAutomaticRifleman
    ears: AU14HeadsetGovforMarine

- type: startingGear
  id: AU14GearGOVFORAutoRiflemanDummy
  equipment:
    outerClothing: AU14ArmorSmartGunJungleCombatHarness
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetGovforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSquadAutomaticRifleman
  name: Spawn Point GOVFOR Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSquadAutomaticRifleman
  - type: Sprite
    state: syn_spawn

- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  id: AU14JobWeaponsSpecialistBaseAbstract
  name: au14-job-name-govforweaponsspecialist
  description: au14-job-description-govforweaponsspecialist
  icon: "AU14JobIconGovWeaponsSpecialist"
  spawnMenuRoleName: Weapons Specialist (GOVFOR)
  startingGear: AU14GearGOVFORWeaponsSpecialist
  dummyStartingGear: AU14GearGOVFORRiflemanDummy
  playTimeTracker: AU14JobGOVFORWeaponsSpecialist
  accessGroups:
  - AU14GovforWeaponsSpecialist

- type: job
  abstract: true
  parent: AU14JobWeaponsSpecialistBaseAbstract
  id: AU14JobWeaponsSpecialistBase
  roundRole: WeaponsSpecialist
  roundProfiles:
  - AU14RoundJobProfileMilitaryBase
  roundComponents:
  - type: Skills
    preset: AU14SkillPresetPlatoonRifleman
  - type: JobPrefix
    prefix: au14-job-prefix-govforweaponsspecialist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14govforjobicons.rsi
      state: govfor_ws

  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankPrivateFirstClass:
      entity: AU14ChevronUSCMPrivateFirstClass
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORWeaponsSpecialist
        time: 36000 # 10 hours
    RMCRankPrivate:
      entity: AU14ChevronUSCMPrivate
      requirements: []
- type: playTimeTracker
  id: AU14JobGOVFORWeaponsSpecialist
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORWeaponsSpecialist
  equipment:
    id: AU14IDCardWeaponsSpecialist
    ears: AU14HeadsetGovforMarine

- type: startingGear
  id: AU14GearGOVFORWSDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetGovforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORWeaponsSpecialist
  name: Spawn Point GOVFOR Weapons Specialist
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORWeaponsSpecialist
  - type: Sprite
    state: syn_spawn

- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRifleman
  hidden: false
  setPreference: true
  basePlaytimeTracker: true

- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobGOVFORSquadAutomaticRifleman
  hidden: false
  setPreference: true
  basePlaytimeTracker: true

- type: job
  parent: AU14JobWeaponsSpecialistBase
  id: AU14JobGOVFORWeaponsSpecialist
  hidden: false
  setPreference: true
  basePlaytimeTracker: true

- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobOPFORSquadRifleman
  roundSide: Opfor
  roundForce: OPFOR
  icon: "AU14JobIconOPFORRifleman"
  spawnMenuRoleName: Rifleman (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearopforSquadRifleman
  dummyStartingGear: AU14GearopforRiflemanDummy
  accessGroups:
  - AU14OpforSquad

- type: startingGear
  id: AU14GearopforSquadRifleman
  equipment:
    id: AU14IDCardopforSquadRifleman
    ears: AU14HeadsetOpforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSquadRifleman
  name: Spawn Point opfor Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORSquadRifleman
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforRiflemanDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetOpforMarine

- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobOPFORSquadAutomaticRifleman
  roundSide: Opfor
  roundForce: OPFOR
  icon: "AU14JobIconOPFORAFN"
  spawnMenuRoleName: Automatic Rifleman (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearopforSquadAutomaticRifleman
  dummyStartingGear: AU14GearopforAutoRiflemanDummy
  accessGroups:
  - AU14OpforGunner
- type: startingGear
  id: AU14GearopforSquadAutomaticRifleman
  equipment:
    id: AU14IDCardopforSquadAutomaticRifleman
    ears: AU14HeadsetOpforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSquadAutomaticRifleman
  name: Spawn Point opfor Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORSquadAutomaticRifleman
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforAutoRiflemanDummy
  equipment:
    outerClothing: AU14ArmorSmartGunJungleCombatHarness
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetOpforMarine

- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRiflemanRMC
  roundForce: RMC
  name: au14-job-name-govforsquadriflemanRMC
  spawnMenuRoleName: Rifleman (TWE RMC)
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMC_LanceCorporal:
      entity: AU14ChevronRMCLanceCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadRifleman
        time: 54000 # 15 hours
    RMC_Marine:
      entity: AU14ChevronRMCMarine
      requirements: []

- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobGOVFORSquadAutomaticRiflemanRMC
  roundForce: RMC
  name: au14-job-name-govforsquadautomaticriflemanRMC
  spawnMenuRoleName: Automatic Rifleman (TWE RMC)
  ranks:
    RMC_Corporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    RMC_LanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 54000 # 15 hours
    RMC_Marine: []

- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRiflemanUPP
  roundForce: UPP
  name: Rifleman
  spawnMenuRoleName: Rifleman (UPP)
  ranks:
    UPP_Gefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 108000 # 30 hours
    UPP_Private: []

- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobGOVFORSquadAutomaticRiflemanUPP
  roundForce: UPP
  name: Machine Gunner
  spawnMenuRoleName: Automatic Rifleman (UPP)
  ranks:
    UPP_Gefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    UPP_Private: []

- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRiflemanWYPMC
  roundForce: WYPMC
  name: PMC Contractor
  spawnMenuRoleName: Rifleman (WYPMC)
  ranks:
    AU14RankWeYuSeniorOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 108000 # 30 hours
    AU14RankWeYuOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 1200 # 2 hours
    AU14RankWeYuRecruit: []

- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobGOVFORSquadAutomaticRiflemanWYPMC
  roundForce: WYPMC
  name: PMC Smartgun Operator
  spawnMenuRoleName: Automatic Rifleman (WYPMC)
  ranks:
    AU14RankWeYuSeniorOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    AU14RankWeYuOperator: []

- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRiflemanCMBCIU
  roundForce: CMBCIU
  name: Tactical Officer
  ranks:
    AU14RankCMBSrDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 108000 # 30 hours
    AU14RankCMBDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 1200 # 2 hours
    AU14RankCMBProbDeputy: []
  spawnMenuRoleName: Operations Officer (CMBCIU)
