- type: job
  parent: CMJobBase
  id: AU14JobCivilianColonist
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianColonist
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-civiliancolonist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: colonist

  name: au14-job-name-civiliancolonist
  description: au14-job-description-civiliancolonist
  setPreference: true
  playTimeTracker: AU14JobCivilianColonist
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianColonist
  icon: "AU14JobIconColonyColonist"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  spawnMenuRoleName: Colonist (CMU)
  accessGroups:
  - Colonist
  roleWeight: 0.25
- type: startingGear
  id: AU14GearCivilianColonist
  equipment:
    id: AU14IDCardColonyColonist

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianColonist
  name: Spawn Point Civilian Colonist
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianColonist
  - type: Sprite
    state: syn_spawn
  - type: ScenarioSpawnMarker
    kind: ClfCivilianSpawn
    tags:
    - force:clf:civilian-spawn:AU14JobCivilianColonist

- type: entity
  parent: CMSpawnPointJobBase
  id: ScenarioClfCivilianColonistSpawnMarker
  name: Spawn Point Civilian Colonist
  suffix: Scenario Anchor
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianColonist
  - type: Sprite
    state: syn_spawn
  - type: ScenarioSpawnMarker
    kind: ClfCivilianSpawn
    tags:
    - force:clf:civilian-spawn:AU14JobCivilianColonist

- type: playTimeTracker
  id: AU14JobCivilianColonist
  isHumanoid: true

- type: job
  parent: CMJobBase
  id: AU14JobCivilianFoodServiceWorker
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianFoodServiceWorker
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 2
      RMCSkillConstruction: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-civilianfoodserviceworker
  - type: AU14FoodServiceWorkerMarker
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: fsw

  name: au14-job-name-civilianfoodserviceworker
  description: au14-job-description-civilianfoodserviceworker
  setPreference: true
  playTimeTracker: AU14JobCivilianFoodServiceWorker
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianFoodServiceWorker
  icon: "AU14JobIconColonyFSW"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  access:
  - AU14AccessShopkeep
  roleWeight: 0.25
- type: startingGear
  id: AU14GearCivilianFoodServiceWorker
  equipment:
    id: AU14IDCardFoodServiceWorker
    outerClothing: RMCMedicalApron

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianFoodServiceWorker
  name: Spawn Point Food Service Worker
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianFoodServiceWorker
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianFoodServiceWorker
  isHumanoid: true

- type: job
  parent: CMJobBase
  id: AU14JobCivilianFreightSystemsSpecialist
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianFreightSystemsSpecialist
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillFirearms: 2
      RMCSkillDomestics: 1
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillPowerLoader: 2
  - type: JobPrefix
    prefix: au14-job-prefix-freightsystemsspecialist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: fss

  name: au14-job-name-civilianfreightsystemsspecialist
  description: au14-job-description-civilianfreightsystemsspecialist
  setPreference: true
  canBeAntag: false
  playTimeTracker: AU14JobCivilianFreightSystemsSpecialist
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianFreightSystemsSpecialist
  icon: "AU14JobIconCivilianFreightSystemsSpecialist"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonyadministrator
  accessGroups:
  - Colonist
  - auengi
  - CMCargoTech
  - AUPrisonStaff
  roleWeight: 0.25
- type: startingGear
  id: AU14GearCivilianFreightSystemsSpecialist
  equipment:
    head: RMCHardhatOrange
    jumpsuit: AU14CivilianBoilerSuitCyan
    outerClothing: RMCHazardVest
    shoes: RMCBootsCorporate
    id: AU14IDCardColonyFreightSystemsSpecialist
  inhand:
  - CMStampApproved

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianFreightSystemsSpecialist
  name: Spawn Point Freight Systems Specialist
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianFreightSystemsSpecialist
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianFreightSystemsSpecialist
  isHumanoid: true

- type: job
  parent: CMJobBase
  id: AU14JobCivilianJournalist
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianJournalist
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-journalist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: journalist

  name: au14-job-name-civilianjournalist
  description: au14-job-description-civilianjournalist
  setPreference: true
  playTimeTracker: AU14JobCivilianJournalist
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianJournalist
  icon: "AU14JobIconColonyJournalist"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  spawnMenuRoleName: Journalist (CMU)
  accessGroups:
  - Colonist
  - aunews
  roleWeight: 0.25
- type: startingGear
  id: AU14GearCivilianJournalist
  equipment:
    outerClothing: AU14CivilianJacketTanPufferVest

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianJournalist
  name: Spawn Point Civilian Journalist
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianJournalist
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianJournalist
  isHumanoid: true

- type: job
  parent: CMJobBase
  id: AU14JobCivilianShopkeep
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianShopkeep
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 2
      RMCSkillConstruction: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-civilianshopkeep
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: shopkeep

  name: au14-job-name-civilianshopkeep
  description: au14-job-description-civilianshopkeep
  setPreference: true
  playTimeTracker: AU14JobCivilianShopkeep
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianShopkeep
  icon: "AU14JobIconColonyShopkeep"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  access:
  - AU14AccessShopkeep
  roleWeight: 0.25
- type: startingGear
  id: AU14GearCivilianShopkeep
  equipment:
    jumpsuit: AU14CivilianWorkwearYellow
    shoes: RMCShoesBlack
    id: AU14IDCardColonyShopkeep
    back: CMSatchel

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianShopkeep
  name: Spawn Point Shopkeep
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianShopkeep
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianShopkeep
  isHumanoid: true

- type: job
  parent: CMJobBase
  id: AU14JobCivilianWasteManagementSpecialist
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianWasteManagementSpecialist
  roundComponents:
  - type: Skills
    skills:
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillPowerLoader: 2
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-civilianwastemanagementspecialist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: wms

  name: au14-job-name-civilianwastemanagementspecialist
  description: au14-job-description-civilianwastemanagementspecialist
  setPreference: true
  playTimeTracker: AU14JobCivilianWasteManagementSpecialist
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianWasteManagementSpecialist
  icon: "AU14JobIconColonyWMS"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  - auengi
  roleWeight: 0.25
- type: startingGear
  id: AU14GearCivilianWasteManagementSpecialist
  equipment:
    jumpsuit: AU14CivilianSanitationClothes
    outerClothing: AU14CivilianFullSuitSanitation
    shoes: RMCBootsCorporate
    id: AU14IDCardColonyWasteManagementSpecialist

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianWasteManagementSpecialist
  name: Spawn Point Waste Management Specialist
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianWasteManagementSpecialist
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianWasteManagementSpecialist
  isHumanoid: true

- type: job
  parent: CMJobBase
  id: AU14JobCivilianMiner
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianMiner
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 2
      RMCSkillVehicles: 2
      RMCSkillDomestics: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-civilianminer
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: colonist

  name: au14-job-name-civilianminer
  description: au14-job-description-civilianminer
  setPreference: true
  playTimeTracker: AU14JobCivilianMiner
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianMiner
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-foreman
  spawnMenuRoleName: Colony Miner (CMU)
  accessGroups:
  - Colonist
  roleWeight: 0.25
- type: startingGear
  id: AU14GearCivilianMiner
  equipment:
    jumpsuit: AU14CivilianKellandMiningClothes
    outerClothing: AU14CivilianHazardVestKellandMiningCorporation
    shoes: RMCBootsCorporate
    id: AU14IDCardColonyColonist

    head: RMCHardhatOrange

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianMiner
  name: Spawn Point Civilian Miner
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianMiner
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianMiner
  isHumanoid: true

- type: job
  parent: CMJobBase
  id: AU14JobCivilianPrisoner
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianPrisoner
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-civilianprisoner
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: prisoner

  name: au14-job-name-civilianprisoner
  description: au14-job-description-civilianprisoner
  setPreference: true
  playTimeTracker: AU14JobCivilianPrisoner
  startingGear: AU14GearCivilianPrisoner
  ranks:
    RMCRankCivilian: []
  icon: "AU14JobIconColonyPrisoner"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-loner
  spawnMenuRoleName: Colony Prisoner (CMU)
  roleWeight: 0.6
- type: startingGear
  id: AU14GearCivilianPrisoner
  equipment:
    jumpsuit: AU14CivilianPrisonJumpsuit
    shoes: RMCShoesBlack

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianPrisoner
  name: Spawn Point Civilian Prisoner
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianPrisoner
  - type: Sprite
    state: syn_spawn

- type: entity
  parent: MarkerBase
  id: auprisonerghost
  name: Prisoner colonist ghost role
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: aughostprisoner

- type: randomHumanoidSettings
  parent: RMCSettingsGhostRole
  id: aughostprisoner
  components:
  - type: RMCJobSpawner
    job: AU14JobCivilianPrisoner

- type: playTimeTracker
  id: AU14JobCivilianPrisoner
  isHumanoid: true

- type: job
  parent: CMJobBase
  id: AU14JobCivilianUSASFRecruiter
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianUSASFRecruiter
  roundComponents:
  - type: Skills
    skills:
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillVehicles: 1
      RMCSkillPowerLoader: 1
      RMCSkillFirearms: 2
      RMCSkillFireman: 1
      RMCSkillJtac: 3
  - type: JobPrefix
    prefix: au14-job-prefix-usasfrecruiter
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: advisor

  name: au14-job-name-usasfrecruiter
  description: au14-job-description-usasfrecruiter
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  playTimeTracker: AU14JobCivilianUSASFRecruiter
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianUSASFRecruiter
  icon: "AU14JobIconColonyAdvisor"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  roleWeight: 0.25
- type: startingGear
  id: AU14GearCivilianUSASFRecruiter
  equipment:
    shoes: RMCBootsCorporate
    pocket1: AU14StampRecruiter

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianUSASFRecruiter
  name: Spawn Point USASF Recruiter LV624 SPECIFIC
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianUSASFRecruiter
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianUSASFRecruiter
  isHumanoid: true
