- type: job
  abstract: true
  parent: CMJobBase
  id: AU14JobWorkingJoeBase
  name: au14-job-name-workingjoe
  description: au14-job-description-workingjoe
  playTimeTracker: AU14JobWorkingJoe
  basePlaytimeTracker: true
  setPreference: true
  canBeAntag: false
  whitelisted: true
  whitelistParent: AU14JobGeneralWhitelist

- type: playTimeTracker
  id: AU14JobWorkingJoe
  isHumanoid: true

- type: startingGear
  id: AU14GearWorkingJoeBase
  equipment:
    shoes: CMBootsBlack
    jumpsuit: CMJumpsuitAverageJoe
    belt: CMBeltUtilityFilled
    back: AU14IMPBackpackWorkingJoe
    pocket1: RMCPouchElectronicsFill
    pocket2: RMCPouchConstructionFillFull
  storage:
      belt:
      - AU14MaintenanceJack
      - RMCSynthResetKeySeegson
      back:
      - AU14SprayCleanerExperimental
      - RMCBucketJanitorial
      - CMMop
      - CMWetSign
      - RMCLightReplacer
      - CMFireExtinguisher
      - AU14StampJoe
  inhand:
  - TrashBag

- type: job
  parent: CMJobBase
  id: AU14JobCivilianColonySynthetic
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianColonySynthetic
  roundComponents:
  - type: NpcFactionMember
    factions:
    - ColonySynth
  - type: Skills
    skills:
      RMCSkillCqc: 4
      RMCSkillEngineer: 4
      RMCSkillConstruction: 3
      RMCSkillOverwatch: 1
      RMCSkillMedical: 4
      RMCSkillSurgery: 3
      RMCSkillResearch: 1
      RMCSkillMeleeWeapons: 2
      RMCSkillPilot: 2
      RMCSkillPolice: 2
      RMCSkillFireman: 5
      RMCSkillFirearms: 2
      RMCSkillPowerLoader: 2
      RMCSkillVehicles: 2
      RMCSkillJtac: 3
      RMCSkillIntel: 2
      RMCSkillDomestics: 2
      RMCSkillNavigations: 1
  - type: JobPrefix
    prefix: au14-job-prefix-civiliancolonysynthetic
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_AU14/Interface/au14colonyjobicons.rsi
      state: synth
  - type: MeleeWeapon
    soundHit:
      path: /Audio/_RMC14/Weapons/synthpunch1.ogg
      params:
        variation: 0.15
        volume: -1
    angle: 30
    animation: WeaponArcFist
    attackRate: 1
    damage:
      types:
        Blunt: 35
  - type: Synth
    generation: "rmc-species-synth-generation-second"

  name: au14-job-name-civiliancolonysynthetic
  description: au14-job-description-civiliancolonysynthetic
  setPreference: true
  canBeAntag: false
  playTimeTracker: AU14JobCivilianColonySynthetic
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 hours
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankSyntheticColonist: []
  startingGear: AU14GearCivilianColonySynthetic
  icon: "AU14JobIconColonySynth"
  hasIcon: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  whitelisted: true
  whitelistParent: AU14JobGeneralWhitelist
  accessGroups:
  - Colonist
  - auadmin
  roleWeight: 0.25
- type: startingGear
  id: AU14GearCivilianColonySynthetic
  equipment:
    shoes: RMCBootsCorporate
    ears: AU14ColonyAdminHeadset

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianColonySynthetic
  name: Spawn Point AU14 Colony Synthetic
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianColonySynthetic
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianColonySynthetic
  isHumanoid: true

- type: job
  parent: AU14JobWorkingJoeBase
  id: AU14JobColonyWorkingJoe
  roundSide: Civilian
  roundForce: WORKING_JOE
  roundRole: ColonyWorkingJoe
  roundProfiles:
  - AU14RoundJobProfileColonyWorkingJoe
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  icon: "AU14JobIconColonyWorkingJoe"
  spawnMenuRoleName: Working Joe (Colony)
  supervisors: au14-job-supervisors-workingjoe-colony
  usePlayerProfile: false
  jobEntity: AU14MobWorkingJoeColony
  jobPreviewEntity: AU14MobWorkingJoeDummy
  hasIcon: false
  accessGroups:
  - auadmin
  - Colonist
  - AUPrisonStaff
  - auwy
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointColonyWorkingJoe
  name: Spawn Point Working Joe (Colony)
  components:
  - type: SpawnPoint
    job_id: AU14JobColonyWorkingJoe
  - type: Sprite
    state: syn_spawn

- type: job
  parent: AU14JobColonyWorkingJoe
  id: AU14JobColonyWorkingJoeHazmat
  roundSide: Civilian
  roundForce: WORKING_JOE
  roundRole: ColonyWorkingJoeHazmat
  roundProfiles:
  - AU14RoundJobProfileColonyWorkingJoe
  roundComponents:
  - type: Loadout
    prototypes: [ AU14GearColonyWorkingJoeHazmat ]

  spawnMenuRoleName: Working Joe (Hazmat)
  dummyStartingGear: AU14GearColonyWorkingJoeHazmat

- type: startingGear
  id: AU14GearColonyWorkingJoeHazmat
  equipment:
    id: AU14IDCardColonyWorkingJoe
    ears: AU14HeadsetWorkingJoe
    shoes: AU14BootsCBRN
    gloves: RMCHandsVeteranCBRN
    jumpsuit: AU14JoeHazmat
    belt: CMBeltUtilityFilled
    back: AU14IMPBackpackWorkingJoe
    pocket2: RMCPouchConstructionFillFull
  storage:
      belt:
      - AU14MaintenanceJack
      - RMCSynthResetKeySeegson
  inhand:
  - CMFireExtinguisher

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointWorkingJoeHazmat
  name: Spawn Point Working Joe (Hazmat)
  components:
  - type: SpawnPoint
    job_id: AU14JobColonyWorkingJoeHazmat
  - type: Sprite
    state: syn_spawn
