using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class EscapeMenu : DefaultWindow
    {
        public EscapeMenu()
        {
            RobustXamlLoader.Load(this);
            SetRoundStatus(string.Empty, string.Empty, 0, 0, string.Empty, false);
        }

        public void SetRoundStatus(string mapName, string shipMapName, int roundId, int playerCount, string gamemode, bool isRoundStarted)
        {
            MapValue.Text = string.IsNullOrWhiteSpace(mapName)
                ? Loc.GetString("ui-escape-status-unknown")
                : mapName;
            ShipMapValue.Text = string.IsNullOrWhiteSpace(shipMapName)
                ? Loc.GetString("ui-escape-status-no-ship")
                : shipMapName;
            RoundValue.Text = roundId > 0
                ? roundId.ToString()
                : Loc.GetString("ui-escape-status-unknown");
            PlayersValue.Text = playerCount.ToString();
            GamemodeValue.Text = string.IsNullOrWhiteSpace(gamemode)
                ? Loc.GetString("ui-escape-status-unknown")
                : gamemode;
            RoundTimeValue.Text = isRoundStarted
                ? FormatRoundTime(TimeSpan.Zero)
                : Loc.GetString("ui-escape-status-not-started");
        }

        public void SetRoundTime(TimeSpan roundTime, bool isRoundStarted)
        {
            RoundTimeValue.Text = isRoundStarted
                ? FormatRoundTime(roundTime)
                : Loc.GetString("ui-escape-status-not-started");
        }

        private static string FormatRoundTime(TimeSpan roundTime)
        {
            if (roundTime < TimeSpan.Zero)
                roundTime = TimeSpan.Zero;

            return $"{(int) roundTime.TotalHours:00}:{roundTime.Minutes:00}";
        }
    }
}
