using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;

namespace Content.Client.AU14.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveIntelWindow : FancyWindow
{
    public ObjectiveIntelWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
