research-database-details = [bold]Database details:[/bold]
cmu-paper-header-wy =[italic][bold]Official Weyland-Yutani Document[/bold][/italic]
# for some really fucked up reason, {"\u000a"} is necessary for newlines
cmu-paper-subheader-xrf-analysis = [italic]Automated A-XRF Report[/italic]{"\u000a"}[head=2]Analysis of {$NAME}[/head]{"\u000a"}[bold]Results for sample:[/bold]#{$NUMBER}
cmu-paper-subheader-research-xrf-fail = [italic]Reagent Analysis Print[/italic]{"\u000a"}[head=2]Analysis ERROR[/head]

cmu-paper-research-fail-reason = [bold]Reason for error:[/bold]{"\u000a"}[italic]{$REASON}[/italic]

cmu-paper-xrf-footer = [italic]This report was automatically generated by the A-XRF Scanner.[/italic]

research-report-reaction-header = Chemical has the following reaction indicators:

research-report-overdose = Overdoses at {$OD} units.
research-report-crit-overdose = Critically overdoses at {$COD} units.
research-report-metab-mult = Standard duration multiplier of {$MULT}x.

research-report-clearance-insuf = CLASSIFIED:[italic] Clearance level {$CLEAR} required to read the database entry.[/italic]
research-report-x-needed = CLASSIFIED:[italic] Clearance level [bold]X[/bold] required to read the database entry.[/italic]

research-report-no-data = [italic]No details on this reagent could be found in the database.[/italic]

research-report-spectrum-saved = [italic]Saved emission spectrum of {$NAME} to the database.[/italic]

research-report-composition-details = [bold]Composition Details:[/bold]

research-report-unknown-emission = [italic]- Unknown emission spectrum.[/italic]

research-report-ingredient = [italic] - {$AMOUNT} {$NAME}[/italic]

research-report-catalyst-details = Reaction would require the following catalysts:

research-report-element = [italic] - {$NAME}[/italic]

research-report-unable-analyze = [italic]ERROR: Unable to analyze emission spectrum of sample.[/italic]

xrf-report-error = Analysis of ERROR

research-report-analysis-name = Analysis of {$NAME1}{$NAME2}

research-report-simulation-name = Simulation result for {$ID}

cmu-paper-header-wy-sim = [italic][bold]Official Company Document[/bold]{"\u000a"}Simulated Synthesis Report[/italic]{"\u000a"}[head=2]Result for {$ID}[/head]

cmu-paper-sim-footer = [italic]This report was automatically printed by the Synthesis Simulator.[/italic]

research-chem-terminal-update = Chemical contracts have been updated!

research-data-ui-clearance = [color=#ffbf00][head=2]Clearance Level {$NUM}[/head][/color]
research-data-ui-credits = [color=#ffbf00][head=2]Credits available: {$NUM}[/head][/color]

research-data-ui-manage = Manage Research
research-data-ui-view = View Chemicals

research-data-ui-chem-name = [color=#ffbf00][head=3]{$NAME}[/head][/color]

research-data-ui-diff-hard = Hard
research-data-ui-diff-inter = Intermediate
research-data-ui-diff-easy = Easy

research-data-ui-chem-difficulty = [color=#ffbf00][head=3]Difficulty: {$DIFF}[/head][/color]

research-data-ui-chem-desc = [color=#ffbf00]Early assesment shows one part of the recipe is {$RECIHINT}{"\u000a"}Early testing shows property of {$PROPHINT}[/color]

research-data-ui-time-left = [color=#ffbf00]Contracts Refresh in: {$TIME}[/color]

research-data-ui-chem-take = [color=#ffbf00][head=3]Take Contract[/head][/color]

research-data-synthesis-name = Synthesis of {$NAME}

research-data-contract-name = Contract for {$NAME}

research-data-ui-analysis-scan = [color=#ffbf00][bold]Analysis[/bold][/color]
research-data-ui-analysis-sim = [color=#ffbf00][bold]Simulation[/bold][/color]
research-data-ui-compound-idx = [color=#ffbf00][bold]{$NAME}[/bold][/color]

research-data-ui-scan-time = [color=#ffbf00][bold]Scan Time[/bold][/color]
research-data-ui-vc-type = [color=#ffbf00][bold]Type[/bold][/color]
research-data-ui-compound = [color=#ffbf00][bold]Compound[/bold][/color]
research-data-ui-actions = [color=#ffbf00][bold]Actions[/bold][/color]

research-data-ui-reprint = [color=#ffbf00][head=3]Reprint Last Contract[/head][/color]
research-data-ui-contracts = [color=#ffbf00][head=3]Chemical Contracts[/head][/color]
research-data-ui-scan-time-idx = [color=#ffbf00][bold]{$TIME}[/bold][/color]
research-data-ui-improve = [color=#ffbf00][head=3]Improve: {$NUM}CR[/head][/color]
ui-research-data-terminal-name = Research Data Terminal

research-data-ui-read = [color=#ffbf00][bold]Read[/bold][/color]
research-data-ui-print = [color=#ffbf00][bold]Print[/bold][/color]