using System.Linq;
using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class AdminConsoleThirdPartyWindow : DefaultWindow
{
    public event Action<string>? OnCallThirdParty;

    private List<string> _thirdPartyIds = new();
    private Dictionary<string, (string DisplayName, float Cost)> _thirdParties = new();

    public AdminConsoleThirdPartyWindow()
    {
        RobustXamlLoader.Load(this);

        ThirdPartySelect.OnItemSelected += args =>
        {
            if (args.Id >= 0 && args.Id < _thirdPartyIds.Count)
            {
                var id = _thirdPartyIds[args.Id];
                if (_thirdParties.TryGetValue(id, out var info))
                    CostLabel.Text = $"Cost: ${info.Cost:F0}";
            }
        };

        CallBtn.OnPressed += _ =>
        {
            if (ThirdPartySelect.SelectedId >= 0 && ThirdPartySelect.SelectedId < _thirdPartyIds.Count)
            {
                OnCallThirdParty?.Invoke(_thirdPartyIds[ThirdPartySelect.SelectedId]);
                StatusLabel.Text = "Requesting support...";
            }
        };
    }

    public void UpdateState(AdminConsoleThirdPartyBuiState s)
    {
        BudgetLabel.Text = $"Colony Budget: ${s.Budget:F0}";
        _thirdParties = s.CallableParties;
        _thirdPartyIds = s.CallableParties.Keys.ToList();
        ThirdPartySelect.Clear();

        if (_thirdPartyIds.Count == 0)
        {
            StatusLabel.Text = "No third parties available.";
            CallBtn.Disabled = true;
            CostLabel.Text = "Cost: N/A";
            return;
        }

        CallBtn.Disabled = false;
        StatusLabel.Text = "";

        for (int i = 0; i < _thirdPartyIds.Count; i++)
        {
            var id = _thirdPartyIds[i];
            var info = s.CallableParties[id];
            ThirdPartySelect.AddItem(info.DisplayName, i);
        }

        if (_thirdPartyIds.Count > 0)
        {
            ThirdPartySelect.SelectId(0);
            if (_thirdParties.TryGetValue(_thirdPartyIds[0], out var first))
                CostLabel.Text = $"Cost: ${first.Cost:F0}";
        }
    }
}

