- type: job
  parent: CMJobBase
  id: AU14JobGOVFORSquadRiflemanCMBCIU
  name: Tactical Officer
  description: au14-job-description-govforsquadrifleman
  setPreference: false
  playTimeTracker: AU14JobGOVFORSquadRiflemanCMBCIU
  ranks:
    AU14RankCMBSrDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRiflemanCMBCIU
      time: 1800 # 30 hours
    AU14RankCMBDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRiflemanCMBCIU
      time: 120 # 2 hours
    AU14RankCMBProbDeputy: []
  startingGear: AU14GearGOVFORSquadRifleman
  dummyStartingGear: AU14GearGOVFORRiflemanDummy
  icon: "AU14JobIconRFN"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14OpforSquad
  hasIcon: false
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 2
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanCMBCIU
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: playTimeTracker
  id: AU14JobGOVFORSquadRiflemanCMBCIU
  isHumanoid: true