- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRiflemanCMBCIU
  name: Tactical Officer
  ranks:
    AU14RankCMBSrDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 108000 # 30 hours
    AU14RankCMBDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 1200 # 2 hours
    AU14RankCMBProbDeputy: []
  spawnMenuRoleName: Operations Officer (CMBCIU)
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanCMBCIU