- type: job
  parent: AU14JobPlatoonCorpsmanBase
  id: AU14JobGOVFORPlatoonCorpsmanCMBCIU
  name: Tactical Medic
  spawnMenuRoleName: Hospital Corpsman (CMBCIU)
  ranks:
    AU14RankCMBSrDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatoonCorpsman
      time: 108000 # 30 hours
    AU14RankCMBDeputy: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatoonCorpsmanCMBCIU
