- type: job
  abstract: true
  parent: CMJobBase
  id: AU14JobWorkingJoeBase
  name: au14-job-name-workingjoe
  description: au14-job-description-workingjoe
  playTimeTracker: AU14JobWorkingJoe
  basePlaytimeTracker: true
  setPreference: true
  canBeAntag: false
  whitelisted: true
  whitelistParent: AU14JobGeneralWhitelist
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NoEnglish
    - UkrainianLanguage
    - PolishLanguage
    - CzechLanguage
    - TurkishLanguage
    - KoreanLanguage
    - ItalianLanguage
    - IrishLanguage
    - FinnishLanguage
    - HungarianLanguage
    - AlbanianLanguage
    - SerbianLanguage
    - LithuanianLanguage
    - ArabicLanguage
    - AfrikaansLanguage
    - DutchLanguage
    - SwahiliLanguage
    - PersianLanguage
    - HindiLanguage
    - VietnameseLanguage
    - PortugueseLanguage
    - IndonesianLanguage
    - FilipinoLanguage
    - UrduLanguage
    - YorubaLanguage
    - EsperantoLanguage
    - LatinLanguage
    - SwedishLanguage
    - BrazilianLanguage
    - SlovakLanguage
    - RomanianLanguage

- type: playTimeTracker
  id: AU14JobWorkingJoe
  isHumanoid: true

- type: startingGear
  id: AU14GearWorkingJoeBase
  equipment:
    shoes: CMBootsBlack
    jumpsuit: CMJumpsuitAverageJoe
    belt: CMBeltUtilityFilled
    back: AU14IMPBackpackWorkingJoe
    pocket1: RMCPouchElectronicsFill
    pocket2: RMCPouchConstructionFillFull
  storage:
      belt:
      - AU14MaintenanceJack
      - RMCSynthResetKeySeegson
      back:
      - AU14SprayCleanerExperimental
      - RMCBucketJanitorial
      - CMMop
      - CMWetSign
      - RMCLightReplacer
      - CMFireExtinguisher
      - AU14StampJoe
  inhand:
  - TrashBag
