using System;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._CMU14.Lobby;

/// <summary>
///     The faction choices, moved off the lobby panel and behind a single "Join the round" button.
///     Four wide buttons plus Observe, Rules and Guidebook made the lobby panel a seven-button slab;
///     the factions are one decision, taken once, so they belong in a popup rather than on the
///     permanent surface.
/// </summary>
/// <remarks>
///     Presentation only. What each choice does still lives in <c>LobbyState</c>, which wires these
///     buttons to the same handlers the old inline buttons used.
/// </remarks>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class JoinRoundWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IStylesheetManager _stylesheetManager = default!;

    public JoinRoundWindow()
    {
        Title = Loc.GetString("cmu-lobby-join-round-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyCrtPalette();

        _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    private void OnCrtUiEnabledChanged(bool _)
    {
        ApplyCrtPalette();
    }

    private void OnCrtUiColorChanged(string _)
    {
        ApplyCrtPalette();
    }

    private void ApplyCrtPalette()
    {
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
    }
}
