using System;
using Content.Client.Lobby.UI;
using Content.Client._CMU14.Interface;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._CMU14.Lobby;

/// <summary>
///     The faction choices, moved off the lobby panel and behind a single "Join the round" button.
///     Four wide buttons plus Observe, Rules and Guidebook made the lobby panel a seven-button slab;
///     the factions are one decision, taken once, so they belong in a popup rather than on the
///     permanent surface.
/// </summary>
/// <remarks>
///     Presentation only. What each choice does still lives in <c>LobbyState</c>, which wires these
///     buttons to the same handlers the old inline buttons used.
/// </remarks>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class JoinRoundWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IStylesheetManager _stylesheetManager = default!;

    public JoinRoundWindow()
    {
        Title = Loc.GetString("cmu-lobby-join-round-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyCrtPalette();

        _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    private void OnCrtUiEnabledChanged(bool _)
    {
        ApplyCrtPalette();
    }

    private void OnCrtUiColorChanged(string _)
    {
        ApplyCrtPalette();
    }

    /// <summary>
    ///     One faction's look: the card's edge and fill, its button, and its body text.
    /// </summary>
    private readonly record struct FactionStyle(Color Edge, Color Fill, Color Button, Color Text);

    /// <summary>
    ///     Colonists. The plain one on purpose - they are the default, least exotic choice, so it
    ///     gets a neutral grey-green rather than a faction colour. Being the only card with no hue
    ///     is itself the signal.
    /// </summary>
    private static readonly FactionStyle ColonistsStyle = new(
        Color.FromHex("#5E6B64"), Color.FromHex("#0E1211"), Color.FromHex("#18201D"), Color.FromHex("#C2CCC6"));

    /// <summary>Govfor keeps the terminal green - it is the house faction and the theme's own hue.</summary>
    private static readonly FactionStyle GovforStyle = new(
        Color.FromHex("#2E6241"), Color.FromHex("#0B1710"), Color.FromHex("#152F20"), Color.FromHex("#8FE9AE"));

    private static readonly FactionStyle OpforStyle = new(
        Color.FromHex("#8C3038"), Color.FromHex("#170C0E"), Color.FromHex("#2A1417"), Color.FromHex("#FF9E9E"));

    /// <summary>Other - mostly xenomorphs, hence purple.</summary>
    private static readonly FactionStyle OtherStyle = new(
        Color.FromHex("#5B4A8C"), Color.FromHex("#120E1B"), Color.FromHex("#1E1830"), Color.FromHex("#CDBCFF"));

    private void ApplyCrtPalette()
    {
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);

        // After the theme walk, never before. ApplyWindow re-tags every control in the tree and hands
        // the buttons the shared CrtButton box; anything set earlier would simply be replaced.
        ApplyFactionStyles();
    }

    /// <summary>
    ///     Paint each card, button and description in its faction's colours.
    /// </summary>
    /// <remarks>
    ///     Overrides rather than style classes throughout. These are four one-off looks that exist
    ///     only in this window, and a class per faction would mean four near-identical rule sets in
    ///     the stylesheet earning nothing. It also has to beat <see cref="CrtLobbyTheme"/>, which has
    ///     just finished putting every button on the same box.
    /// </remarks>
    private void ApplyFactionStyles()
    {
        Apply(ColonistsCard, JoinColonistsButton, JoinColonistsDesc, "cmu-lobby-join-colonists-desc", ColonistsStyle, buttonOnLeft: true);
        Apply(GovforCard, JoinGovforButton, JoinGovforDesc, "cmu-lobby-join-govfor-desc", GovforStyle, buttonOnLeft: false);
        Apply(OpforCard, JoinOpforButton, JoinOpforDesc, "cmu-lobby-join-opfor-desc", OpforStyle, buttonOnLeft: true);
        Apply(OtherCard, JoinOtherButton, JoinOtherDesc, "cmu-lobby-join-other-desc", OtherStyle, buttonOnLeft: false);
    }

    private static void Apply(
        PanelContainer card,
        Button button,
        RichTextLabel description,
        string locKey,
        FactionStyle style,
        bool buttonOnLeft)
    {
        // The card carries the only full border in the window. A 1px edge is enough to bound it
        // without turning the list into four heavy boxes - the fill is doing most of the separating.
        card.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = style.Fill,
            BorderColor = style.Edge,
            BorderThickness = new Thickness(1),
        };

        // The button is a segment of the card rather than a control placed on it: it fills the card's
        // full height and runs flush into the border, and its only edge is the single rule facing the
        // text. Bordering all four sides here would put a box inside a box, which is the one thing
        // this theme has consistently refused.
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = style.Button,
            BorderColor = style.Edge,
            BorderThickness = buttonOnLeft
                ? new Thickness(0, 0, 1, 0)
                : new Thickness(1, 0, 0, 0),
            ContentMarginLeftOverride = 12,
            ContentMarginRightOverride = 12,
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 4,
        };

        button.Label.FontColorOverride = style.Text;
        button.Label.HorizontalExpand = true;
        button.Label.Align = Label.AlignMode.Center;

        // Dimmed against the button's own text so the button stays the thing the eye lands on.
        description.SetMessage(Loc.GetString(locKey), defaultColor: style.Text.WithAlpha(0.72f));
    }
}
