- type: job
  parent: CMJobBase
  id: AU14JobOpforDSPilot
  name: au14-job-name-opfordspilot
  description: au14-job-description-opfordspilot
  setPreference: true
  canBeAntag: false

  playTimeTracker: AU14JobOpforDSPilot
  ranks:
    RMCRankCaptain:
    - !type:RoleTimeRequirement
      role: AU14JobOpforDSPilot
      time: 7200 # 120 hours
    RMCRankFirstLT:
    - !type:RoleTimeRequirement
      role: AU14JobOpforDSPilot
      time: 3600 # 60 hours
    RMCRankSecondLT: []
  startingGear: AU14GearopforDSPilot
  dummyStartingGear: AU14GearopforDSPilotDummy
  icon: "AU14JobIconOPFORPilotOfficer"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforPilot
  - AU14OpforCorpsman
  - AU14OpforSquad
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 2
        RMCSkillOverwatch: 1
        RMCSkillPilot: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-opfordspilot
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearopforDSPilot
  equipment:
    id: AU14IDCardopforDSPilot
    ears: AU14HeadsetSectionLeaderopfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforDSPilot
  name: Spawn Point opfor Dropship Pilot
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforDSPilot
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobOpforDSPilot
  isHumanoid: true

- type: startingGear
  id: AU14GearopforDSPilotDummy
  equipment:
    outerClothing: AU14USASFICPS2
    shoes: CMBootsBrown
    mask: AU14MaskUSASFPilotOxygen
    head: AU14USASFAirCrewHelmet
    jumpsuit: AU14USASFPilotJumpsuit
    ears: AU14HeadsetSectionLeaderopfor
