- type: job
  parent: CMJobBase
  id: AU14JobOpforSquadAutomaticRifleman
  name: au14-job-name-opforsquadautomaticrifleman
  description: au14-job-description-opforsquadautomaticrifleman
  setPreference: true
  playTimeTracker: AU14JobOpforSquadAutomaticRifleman
  ranks:
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobOpforSquadAutomaticRifleman
      time: 3600 # 60 hours
    RMCRankLanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobOpforSquadAutomaticRifleman
      time: 1800 # 30 hours
    RMCRankPrivateFirstClass:
    - !type:RoleTimeRequirement
      role: AU14JobOpforSquadAutomaticRifleman
      time: 900 # 15 hours
    RMCRankPrivate: []
  startingGear: AU14GearopforSquadAutomaticRifleman
  dummyStartingGear: AU14GearopforAutoRiflemanDummy
  icon: "AU14JobIconOPFORAFN"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforGunner
  overwatchSortPriority: -3
  overwatchShowName: true
  overwatchRoleName: Automatic Rifleman
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillSmartGun: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: au14-job-prefix-opforsquadautomaticrifleman
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: smartgunner
  hidden: false

- type: startingGear
  id: AU14GearopforSquadAutomaticRifleman
  equipment:
    id: AU14IDCardopforSquadAutomaticRifleman
    ear: AU14HeadsetSectionOpfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSquadAutomaticRifleman
  name: Spawn Point opfor Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforSquadAutomaticRifleman
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobOpforSquadAutomaticRifleman
  isHumanoid: true

- type: startingGear
  id: AU14GearopforAutoRiflemanDummy
  equipment:
    outerClothing: AU14ArmorSmartGunJungleCombatHarness
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionOpfor
