using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.CCVar;
using Robust.Client.Graphics;
using Robust.Shared.Configuration;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        private const float BalanceRatingBottomMargin = 84f;

        /// <summary>
        ///     The round timer now lives inside the server-info block so it sits between the round
        ///     table and the player count. Exposed here so LobbyState can keep driving it.
        /// </summary>
        public Label StationTime => ServerInfo.RoundTimeLabel;

        [Dependency] private IClientConsoleHost _consoleHost = default!;
        [Dependency] private IConfigurationManager _cfg = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            PositionBalanceRatingContainer();
            CrtLobbyTheme.Apply(MainContainer);

            // Keep the chat's usual dark backing, but drop its border so it reads as a band running
            // the full width of the lobby panel rather than a second rectangle inside it. The chat
            // deliberately keeps its own colour instead of the CRT palette - it has to stay legible.
            // Only the lobby does this; the in-round chat floats over the game and still needs its
            // outline. The negative margins in the XAML are what let this backing reach the edges.
            // Swap the style class rather than setting PanelOverride: a colour baked into a control
            // goes stale when the CRT palette changes, whereas the stylesheet is rebuilt.
            Chat.ChatWindowPanel.RemoveStyleClass(StyleNano.StyleClassChatPanel);
            Chat.ChatWindowPanel.AddStyleClass(StyleNano.StyleClassCrtChatPanel);

            // Same treatment for the input row, so its border tracks the palette too.
            Chat.ChatInput.RemoveStyleClass(StyleNano.StyleClassChatSubPanel);
            Chat.ChatInput.AddStyleClass(StyleNano.StyleClassCrtChatInput);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);

            SetUpServerInfoCrt();
            _cfg.OnValueChanged(CCVars.CMUCrtMenuEffect, OnMenuEffectChanged);
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtEnabledChanged);
        }

        private void OnMenuEffectChanged(bool _) => SetUpServerInfoCrt();
        private void OnCrtEnabledChanged(bool _) => SetUpServerInfoCrt();

        /// <summary>
        ///     The full prop-terminal treatment on the server info panel - curvature, roll bar,
        ///     grain, the lot - straight off the shared cvars rather than toned down. This is the
        ///     surface to find out on: it is read in glances rather than studied, so if a moving
        ///     artifact is going to be tolerable anywhere in the real UI, it is here.
        /// </summary>
        private void SetUpServerInfoCrt()
        {
            // A style class, not a hand-set PanelOverride: a class-based rule re-resolves every
            // time the stylesheet rebuilds, where reading StyleNano.CrtPanelBackground once and
            // storing the result is a snapshot that only ever reflects the state at the moment this
            // method happened to run. That snapshot is what let a base-mode client show the
            // CRT-enabled colour here - this method's first call landed before StylesheetManager had
            // corrected _crtUiEnabled from the class's compile-time default of true. Applying the
            // class once, here, is enough - see StyleClassCrtPanelFill.
            if (!ServerInfoBacking.HasStyleClass(StyleNano.StyleClassCrtPanelFill))
                ServerInfoBacking.AddStyleClass(StyleNano.StyleClassCrtPanelFill);

            ServerInfoCrt.Source = ServerInfoContent;
            ServerInfoCrt.Phosphor = StyleNano.CrtGreen;
            ServerInfoCrt.Visible = _cfg.GetCVar(CCVars.CMUCrtMenuEffect) && StyleNano.CrtUiEnabled;
        }

        public void PositionBalanceRatingContainer()
        {
            SetAnchorAndMarginPreset(BalanceRatingContainer, LayoutPreset.BottomLeft, margin: 10);
            SetMarginTop(
                BalanceRatingContainer,
                -BalanceRatingContainer.DesiredSize.Y - BalanceRatingBottomMargin);
            SetMarginBottom(BalanceRatingContainer, -BalanceRatingBottomMargin);
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
