- type: job
  parent: AU14JobDCCBase
  id: AU14JobGOVFORDCCUPP
  name: Dropship Crew Chief
  spawnMenuRoleName: Dropship Crew Chief (UPP)
  ranks:
    UPP_FirstSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 360000 # 100 hours
    UPP_SeniorSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 108000 # 30 hours
    UPP_Sergeant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORDCCUPP
    - type: Language
      preset: AU14LanguagePresetUPPEnlisted
