- type: job
  parent: AU14JobDSPilotBase
  id: AU14JobGOVFORDSPilotUPP
  name: Dropship Pilot
  spawnMenuRoleName: Pilot Officer (UPP)
  ranks:
    UPP_Lieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 360000 # 100 hours
    UPP_JuniorLieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 216000 # 60 hours
    UPP_SeniorWarrantOfficer:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 108000 # 30 hours
    UPP_WarrantOfficer: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORDSPilotUPP
    - type: Language
      preset: AU14LanguagePresetUPPOfficer
