- type: job
  parent: AU14JobSectionSergeantBase
  id: AU14JobGOVFORSectionSergeantUPP
  name: Platoon Leader
  spawnMenuRoleName: Platoon Sergeant (UPP)
  ranks:
    UPP_FirstSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSectionSergeant
      time: 216000 # 60 hours
    UPP_SeniorSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSectionSergeant
      time: 108000 # 30 hours
    UPP_Sergeant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSectionSergeantUPP
    - type: Language
      preset: AU14LanguagePresetUPPOfficer
