- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRiflemanUPP
  name: Rifleman
  spawnMenuRoleName: Rifleman (UPP)
  ranks:
    UPP_Gefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 108000 # 30 hours
    UPP_Private: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanUPP
    - type: Language
      preset: AU14LanguagePresetUPPEnlisted
