- type: job
  parent: AU14JobSectionSergeantBase
  id: AU14JobGOVFORSectionSergeantRMC
  name: au14-job-name-govforSSGRMC
  spawnMenuRoleName: Platoon Sergeant (TWE RMC)
  ranks:
    RMC_ColourSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSectionSergeant
      time: 216000 # 60 hours
    RMC_Sergeant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-govforSSGRMC
