- type: job
  parent: AU14JobDCCBase
  id: AU14JobGOVFORDCCRMC
  name: au14-job-name-govfordccRMC
  spawnMenuRoleName: Dropship Crew Chief (TWE RMC)
  ranks:
    RMC_WarrantOfficer1:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 360000 # 100 hours
    RMC_WarrantOfficer2:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 216000 # 60 hours
    RMC_ColourSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 43200 # 12 hours
    RMC_Sergeant: []
