- type: job
  parent: [ AU14JobadvisorBase, AU14JobMilitaryBase ]
  id: AU14JobGOVFORadvisorRMC
  name: au14-job-name-govforadvisor
  description: au14-job-description-govforadvisor
  ranks:
    RMC_WarrantOfficer1:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORadvisor
      time: 360000 # 100 hours
    RMC_WarrantOfficer2: []
  startingGear: AU14GearGOVFORadvisor
  dummyStartingGear: AU14GearGOVFORadvisorDummy
  icon: "AU14JobIconGovAdvisor"
  spawnMenuRoleName: Platoon Advisor (TWE RMC)
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-govforadvisor
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true

- type: startingGear
  id: AU14GearRMCadvisor
  equipment:
    id: AU14IDCardRMCAdvisor
    ears: AU14HeadsetSectionLeader
    back: AU14SatchelMarineAdvisorMilitary