- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRiflemanRMC
  name: au14-job-name-govforsquadriflemanRMC
  spawnMenuRoleName: Rifleman (TWE RMC)
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMC_LanceCorporal:
      entity: AU14ChevronRMCLanceCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadRifleman
        time: 54000 # 15 hours
    RMC_Marine:
      entity: AU14ChevronRMCMarine
      requirements: []
