using Content.Client._RMC14.Language.Systems;
using System.Linq;
using Content.Shared._RMC14.Language.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.ContentPack;

namespace Content.Client._RMC14.UserInterface.Systems.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IResourceManager _resource = default!;

    private static readonly IReadOnlyDictionary<ProtoId<LanguagePrototype>, LanguageLearningViewData> EmptyLearningLanguages =
        new Dictionary<ProtoId<LanguagePrototype>, LanguageLearningViewData>();

    private static readonly StyleBoxFlat FlatTransparent = new()
    {
        BackgroundColor = Color.Transparent,
        BorderThickness = new Thickness(0)
    };

    private const int MaxRecent = 8;

    private ProtoId<LanguagePrototype>? _currentLanguage;
    private IReadOnlySet<ProtoId<LanguagePrototype>> _knownLanguages = new HashSet<ProtoId<LanguagePrototype>>();
    private IReadOnlyDictionary<ProtoId<LanguagePrototype>, LanguageLearningViewData> _learningLanguages = EmptyLearningLanguages;

    private readonly Dictionary<ProtoId<LanguagePrototype>, bool> _expansionStates = [];
    private readonly Dictionary<ProtoId<LanguagePrototype>, bool> _descriptionExpansionStates = [];
    private readonly List<ProtoId<LanguagePrototype>> _recentLanguages = [];

    private LanguageFavorites _favorites = default!;

    // filter state: null = All, "favorites", "recent"
    private string? _activeFilter = null;

    public event Action<ProtoId<LanguagePrototype>>? OnLanguageSelected;

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _favorites = new LanguageFavorites(_resource);

        SetupTabs();
        SetupStyling();
        SetupFilters();
        SetupSearch();
    }

    private void SetupTabs()
    {
        TabContainer.SetTabTitle(KnownLanguagesTab, Loc.GetString("language-menu-known-tab"));
        TabContainer.SetTabTitle(LearningTab, Loc.GetString("language-menu-learning-tab"));
    }

    private void SetupStyling()
    {
        MainContainer.PanelOverride = FlatTransparent;
        ContentContainer.PanelOverride = FlatTransparent;
        KnownLanguagesContainer.PanelOverride = FlatTransparent;
        LearningLanguagesContainer.PanelOverride = FlatTransparent;
        TabContainer.PanelStyleBoxOverride = FlatTransparent;
    }

    private void SetupFilters()
    {
        FilterAll.OnPressed += _ =>
        {
            _activeFilter = null;
            UpdateFilterButtons();
            RebuildKnownList();
        };

        FilterFavorites.OnPressed += _ =>
        {
            _activeFilter = "favorites";
            UpdateFilterButtons();
            RebuildKnownList();
        };

        FilterRecent.OnPressed += _ =>
        {
            _activeFilter = "recent";
            UpdateFilterButtons();
            RebuildKnownList();
        };
    }

    private void SetupSearch()
    {
        SearchBar.OnTextChanged += _ => RebuildKnownList();
    }

    private void UpdateFilterButtons()
    {
        FilterAll.Pressed = _activeFilter == null;
        FilterFavorites.Pressed = _activeFilter == "favorites";
        FilterRecent.Pressed = _activeFilter == "recent";
    }

    public void UpdateLanguages(
        ProtoId<LanguagePrototype> currentLanguage,
        IReadOnlySet<ProtoId<LanguagePrototype>> knownLanguages,
        IReadOnlyDictionary<ProtoId<LanguagePrototype>, LanguageLearningViewData> learningLanguages)
    {
        _currentLanguage = currentLanguage;
        _knownLanguages = knownLanguages;
        _learningLanguages = learningLanguages;

        RebuildKnownList();

        var sortedLearning = GetSortedLearningLanguages();
        UpdateLearningTab(sortedLearning);

        var hasLearning = sortedLearning.Count > 0;
        TabContainer.SetTabVisible(LearningTab, hasLearning);
        if (!hasLearning)
            TabContainer.CurrentTab = 0;
    }

    private void RebuildKnownList()
    {
        KnownLanguageList.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        IEnumerable<ProtoId<LanguagePrototype>> filtered = _activeFilter switch
        {
            "favorites" => _knownLanguages.Where(l => _favorites.Contains(l.Id)),
            "recent"    => _recentLanguages.Where(l => _knownLanguages.Contains(l)),
            _           => _knownLanguages,
        };

        filtered = filtered
            .Where(lang => _prototypeManager.TryIndex<LanguagePrototype>(lang, out var p) && !p.IsInvisibleLanguage)
            .Where(lang =>
            {
                if (string.IsNullOrEmpty(search))
                    return true;
                return _prototypeManager.TryIndex<LanguagePrototype>(lang, out var p) &&
                       p.LocalizedName.ToLowerInvariant().Contains(search);
            })
            .OrderBy(lang => _prototypeManager.Index<LanguagePrototype>(lang).LocalizedName);

        foreach (var languageId in filtered)
        {
            if (!_prototypeManager.TryIndex<LanguagePrototype>(languageId, out var proto))
                continue;

            // Row: [★] [LanguageButton]
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 4,
            };

            var isFav = _favorites.Contains(languageId.Id);
            var favBtn = new Button
            {
                Text = isFav ? "★" : "☆",
                MinWidth = 30,
                MaxWidth = 30,
                ToolTip = isFav ? "Remove from favorites" : "Add to favorites",
            };
            var capturedId = languageId;
            favBtn.OnPressed += _ =>
            {
                _favorites.Toggle(capturedId.Id);
                RebuildKnownList();
            };
            row.AddChild(favBtn);

            var button = new LanguageButton(proto, languageId == _currentLanguage);
            button.HorizontalExpand = true;
            button.OnPressed += _ =>
            {
                OnLanguageSelected?.Invoke(capturedId);
                AddRecent(capturedId);
            };

            if (_descriptionExpansionStates.GetValueOrDefault(languageId, false))
                button.SetDescriptionExpanded(true);

            button.OnDescriptionExpansionChanged += (langId, expanded) =>
                _descriptionExpansionStates[langId] = expanded;

            row.AddChild(button);
            KnownLanguageList.AddChild(row);
        }

        if (!KnownLanguageList.Children.Any())
        {
            KnownLanguageList.AddChild(new Label
            {
                Text = "No languages found.",
                FontColorOverride = Color.FromHex("#888888"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 12),
            });
        }
    }

    private void AddRecent(ProtoId<LanguagePrototype> languageId)
    {
        _recentLanguages.Remove(languageId);
        _recentLanguages.Insert(0, languageId);
        if (_recentLanguages.Count > MaxRecent)
            _recentLanguages.RemoveAt(_recentLanguages.Count - 1);
    }

    private void UpdateLearningTab(IReadOnlyList<ProtoId<LanguagePrototype>> sortedLearningLanguages)
    {
        var existingControls = CacheExistingControls();
        LearningLanguageList.RemoveAllChildren();
        foreach (var languageId in sortedLearningLanguages)
        {
            var progressControl = CreateOrUpdateProgressControl(languageId, existingControls);
            if (progressControl != null)
                LearningLanguageList.AddChild(progressControl);
        }
    }

    private Dictionary<ProtoId<LanguagePrototype>, LanguageLearningProgressControl> CacheExistingControls()
    {
        var existing = new Dictionary<ProtoId<LanguagePrototype>, LanguageLearningProgressControl>();
        foreach (var child in LearningLanguageList.Children.OfType<LanguageLearningProgressControl>())
            existing[child.LanguageId] = child;
        return existing;
    }

    private List<ProtoId<LanguagePrototype>> GetSortedLearningLanguages()
    {
        return _learningLanguages.Keys
            .Where(IsVisibleLearnableLanguage)
            .OrderBy(lang => _prototypeManager.Index<LanguagePrototype>(lang).LocalizedName)
            .ToList();
    }

    private bool IsVisibleLearnableLanguage(ProtoId<LanguagePrototype> language)
    {
        if (!_prototypeManager.TryIndex<LanguagePrototype>(language, out var proto) || proto.IsInvisibleLanguage)
            return false;
        return !_learningLanguages.TryGetValue(language, out var data) || data.IsVisible;
    }

    private LanguageLearningProgressControl? CreateOrUpdateProgressControl(
        ProtoId<LanguagePrototype> languageId,
        Dictionary<ProtoId<LanguagePrototype>, LanguageLearningProgressControl> existingControls)
    {
        if (!_prototypeManager.TryIndex(languageId, out var proto) ||
            !_learningLanguages.TryGetValue(languageId, out var progressData))
            return null;

        if (existingControls.TryGetValue(languageId, out var existing))
        {
            existing.UpdateData(proto, progressData);
            return existing;
        }

        var control = new LanguageLearningProgressControl(proto, progressData);

        if (_expansionStates.GetValueOrDefault(languageId, false))
            control.SetExpanded(true);

        control.OnExpansionChanged += (langId, expanded) => _expansionStates[langId] = expanded;
        return control;
    }
}