using System.Numerics;
using Content.Shared.CMU14.TacticalMap.Reconstruction;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.TacticalMap.Reconstruction;

[GenerateTypedNameReferences]
public sealed partial class CMUReconstructionWindow : DefaultWindow
{
    public Action<CMUReconRouteMessage>? OnRoute;
    public Action<CMUReconCancelOrderMessage>? OnCancelOrder;
    public Action? OnClear;
    public Action<CMUReconSendMessage>? OnSend;
    public Action<CMUReconMapChoice>? OnMapSelected;
    public bool CenterOnOpening { get; set; }
    private bool _centerPending;
    private int _requestId;
    private readonly Dictionary<CMUReconMapChoice, (CMUReconDraft Draft, CMUReconCamera Camera)> _views = new();
    private bool _canOrder;
    private CMUReconSnapshotMessage? _incoming;
    private CMUReconContactsMessage? _incomingContacts;
    public bool IsRefreshing { get; private set; }
    public CMUReconstructionControl SurveyView => View;

    public CMUReconstructionWindow()
    {
        RobustXamlLoader.Load(this);
        SetSize = Vector2.Clamp(UserInterfaceManager.RootControl.Size - new Vector2(24), MinSize, new Vector2(1280, 820));
        InitializeRoutes();
        Floor.OnItemSelected += args =>
        {
            Floor.SelectId(args.Id);
            View.CancelStroke();
            View.SelectLevel(args.Id);
        };
        TopDown.OnPressed += _ => View.SetTopDown();
        Reset.OnPressed += _ => View.ResetCamera();
        CenterPlayer.OnPressed += _ => { if (View.CenterOnPlayer() && View.Scene is { } scene) ConfigureFloors(scene); };
        MapSelection.OnItemSelected += args =>
        {
            var choice = (CMUReconMapChoice) args.Id;
            if (View.Scene?.MapChoice != choice && !View.Draft.Sending) OnMapSelected?.Invoke(choice);
        };
        LowWalls.OnToggled += args => View.SetLowWalls(args.Pressed);
        Isolate.OnToggled += args => View.SetIsolated(args.Pressed);
        Labels.OnToggled += args => View.ShowLabels = args.Pressed;
        Contacts.OnToggled += args => View.ShowContacts = args.Pressed;
    }

    public void Receive(BoundUserInterfaceMessage message)
    {
        if (message is CMUReconSnapshotMessage requested && requested.RequestId != _requestId) return;
        if (message is CMUReconFeedbackMessage { LocalizationKey: "cmu-recon-no-map" } failed && failed.RequestId != _requestId) return;
        switch (message)
        {
            case CMUReconContactsMessage contacts:
                if (_incoming?.Generation == contacts.Generation)
                {
                    _incomingContacts = contacts;
                    // The replacement atlas has the same world coordinates. Contacts are independent of terrain loading.
                    View.TrackedContacts = contacts.Contacts;
                }
                if (_incoming == null && View.Scene is { } tracked && tracked.Generation == contacts.Generation)
                {
                    View.TrackedContacts = contacts.Contacts;
                    tracked.OperatorPosition = contacts.OperatorPosition;
                    tracked.OperatorDepth = contacts.OperatorDepth;
                }
                break;
            case CMUReconSentMessage sent:
                if (View.Draft.Acknowledge(sent))
                {
                    if (sent.Accepted && View.Scene is { } submitted)
                        View.Orders = submitted.Orders = sent.Orders;
                    Status.Text = Loc.GetString(sent.Accepted ? "cmu-recon-order-sent" : "cmu-recon-send-failed");
                }
                break;
            case CMUReconSnapshotMessage scene:
                if (IsRefreshing && View.Scene != null)
                {
                    if (View.TryResume(scene))
                    {
                        _incoming = null;
                        IsRefreshing = false;
                        _canOrder = scene.CanOrder;
                        ApplyOpeningCenter();
                        ConfigureFloors(scene);
                        ConfigureMaps(scene);
                        Feed.Text = Loc.GetString("cmu-recon-feed");
                        Status.Text = Loc.GetString("cmu-recon-live");
                        break;
                    }
                    if (CMUReconSceneData.Initialize(scene))
                    {
                        _incoming = scene;
                        var saved = View.Scene;
                        if (saved.MapChoice == scene.MapChoice && saved.Origin == scene.Origin &&
                            saved.Width == scene.Width && saved.Height == scene.Height &&
                            saved.MinDepth == scene.MinDepth && saved.Levels == scene.Levels)
                        {
                            // Fresh operator data is enough to center a retained map. Do not wait
                            // for every geometry chunk, or recenter again after the player pans.
                            saved.OperatorPosition = scene.OperatorPosition;
                            saved.OperatorDepth = scene.OperatorDepth;
                            ApplyOpeningCenter();
                            ConfigureFloors(saved);
                        }
                    }
                    break;
                }
                View.SetScene(scene);
                if (_views.TryGetValue(scene.MapChoice, out var previous))
                {
                    View.Draft = previous.Draft;
                    View.RestoreCamera(previous.Camera);
                    LowWalls.Pressed = previous.Camera.LowWalls;
                    Isolate.Pressed = previous.Camera.Isolated;
                    Labels.Pressed = previous.Camera.Labels;
                }
                else View.Draft = new CMUReconDraft();
                ApplyOpeningCenter();
                _canOrder = scene.CanOrder;
                ConfigureFloors(scene);
                ConfigureMaps(scene);
                Status.Text = Loc.GetString("cmu-recon-live");
                break;
            case CMUReconPatchMessage patch:
                if (IsRefreshing)
                {
                    if (_incoming is not { } incoming || incoming.Generation != patch.Generation) return;
                    CMUReconSceneData.Apply(incoming, patch);
                    if (incoming.LoadedChunks != incoming.TotalChunks) break;
                    var camera = View.CaptureCamera();
                    View.SetScene(incoming);
                    if (_incomingContacts is { } latest)
                    {
                        View.TrackedContacts = latest.Contacts;
                        incoming.OperatorPosition = latest.OperatorPosition;
                        incoming.OperatorDepth = latest.OperatorDepth;
                    }
                    View.RestoreCamera(camera);
                    ApplyOpeningCenter();
                    ConfigureFloors(incoming);
                    ConfigureMaps(incoming);
                    _incoming = null;
                    IsRefreshing = false;
                    Feed.Text = Loc.GetString("cmu-recon-feed");
                    _canOrder = incoming.CanOrder;
                    Status.Text = Loc.GetString("cmu-recon-live");
                    break;
                }
                if (View.Scene?.Generation != patch.Generation) return;
                View.Apply(patch);
                _canOrder = patch.CanOrder;
                break;
            case CMUReconFeedbackMessage feedback:
                Status.Text = Loc.GetString(feedback.LocalizationKey);
                if (feedback.LocalizationKey == "cmu-recon-no-map")
                {
                    _incoming = null;
                    View.ClearScene();
                    IsRefreshing = false;
                    _canOrder = false;
                }
                break;
        }
        if ((_incoming ?? View.Scene) is { } current)
            Progress.Text = current.LoadedChunks < current.TotalChunks
                ? Loc.GetString("cmu-recon-progress", ("percent", current.TotalChunks == 0 ? 0 : 100 * current.LoadedChunks / current.TotalChunks))
                : "";
        UpdateDrawingControls();
        CenterPlayer.Disabled = IsRefreshing || View.Scene?.OperatorPosition == null;
        MapSelection.Disabled = View.Scene == null || View.Draft.Sending;
    }

    public void BeginViewRequest(int requestId, bool keepScene = false)
    {
        View.FinishStroke();
        if (View.Scene is { } scene) _views[scene.MapChoice] = (View.Draft, View.CaptureCamera());
        _requestId = requestId;
        _centerPending = CenterOnOpening;
        _incoming = null;
        _incomingContacts = null;
        if (!keepScene) View.ClearScene();
        IsRefreshing = keepScene && View.Scene != null;
        _canOrder = false;
        MapSelection.Disabled = CenterPlayer.Disabled = true;
        Status.Text = Loc.GetString(IsRefreshing ? "cmu-recon-refreshing" : "cmu-recon-loading");
        UpdateDrawingControls();
    }

    private void ApplyOpeningCenter()
    {
        if (_centerPending) View.CenterOnPlayer();
        _centerPending = false;
    }

    private void ConfigureMaps(CMUReconSnapshotMessage scene)
    {
        MapSelection.Clear();
        if (scene.HasPlanet) MapSelection.AddItem(Loc.GetString("cmu-recon-planet"), (int) CMUReconMapChoice.Planet);
        if (scene.HasShip) MapSelection.AddItem(Loc.GetString("cmu-recon-ship"), (int) CMUReconMapChoice.Ship);
        if (scene.HasPlanet || scene.HasShip) MapSelection.SelectId((int) scene.MapChoice);
    }

    public void RestoreCached(CMUReconSnapshotMessage scene, CMUReconCamera camera)
    {
        View.SetScene(scene);
        View.RestoreCamera(camera);
        ConfigureFloors(scene);
        ConfigureMaps(scene);
        LowWalls.Pressed = camera.LowWalls;
        Isolate.Pressed = camera.Isolated;
        Labels.Pressed = camera.Labels;
        IsRefreshing = true;
        _canOrder = false;
        Status.Text = Loc.GetString("cmu-recon-refreshing");
        Feed.Text = Loc.GetString("cmu-recon-feed-saved");
        UpdateDrawingControls();
    }

    private void ConfigureFloors(CMUReconSnapshotMessage scene)
    {
        Floor.Clear();
        for (var i = 0; i < scene.Levels; i++)
            Floor.AddItem(Loc.GetString("cmu-recon-level", ("z", scene.MinDepth + i)), i);
        Floor.SelectId(View.SelectedLevel);
    }
}
